import { useState } from 'react';
import { Download, Printer, Mail, MessageCircle, MoreHorizontal, Share2, FileSpreadsheet } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { toast } from 'sonner';
import { openWhatsAppShare } from '@/lib/share';

interface ReconciliationShareActionsProps {
  accountName: string;
  statementDate: string;
  statementBalance: number;
  reconciledBalance: number;
  difference: number;
  onExportPdf: () => void;
  onExportExcel?: () => void;
  organizationName?: string;
  reconciliationType?: 'bank' | 'credit-card';
}

export function ReconciliationShareActions({
  accountName,
  statementDate,
  statementBalance,
  reconciledBalance,
  difference,
  onExportPdf,
  onExportExcel,
  organizationName,
  reconciliationType = 'bank',
}: ReconciliationShareActionsProps) {
  const [emailDialogOpen, setEmailDialogOpen] = useState(false);
  const [emailTo, setEmailTo] = useState('');
  const [emailSubject, setEmailSubject] = useState('');
  const [emailBody, setEmailBody] = useState('');

  const formatCurrency = (amount: number) =>
    new Intl.NumberFormat('en-CA', { style: 'currency', currency: 'CAD' }).format(amount);

  const formatDate = (dateStr: string) => {
    try {
      return new Date(dateStr).toLocaleDateString('en-CA', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      });
    } catch {
      return dateStr;
    }
  };

  const getShareMessage = () => {
    const typeLabel = reconciliationType === 'credit-card' ? 'Credit Card' : 'Bank';
    const statusEmoji = Math.abs(difference) < 0.01 ? '✅' : '⚠️';
    const statusText = Math.abs(difference) < 0.01 ? 'RECONCILED' : `DIFFERENCE: ${formatCurrency(difference)}`;
    
    return `${typeLabel} Reconciliation Report

${organizationName ? `Organization: ${organizationName}\n` : ''}Account: ${accountName}
Statement Date: ${formatDate(statementDate)}

Statement Balance: ${formatCurrency(statementBalance)}
Reconciled Balance: ${formatCurrency(reconciledBalance)}

${statusEmoji} Status: ${statusText}

Generated by EFINSUITE Globe`;
  };

  const handlePrint = () => {
    // Generate PDF and trigger print
    onExportPdf();
    toast.success('PDF generated. Use your PDF viewer to print.');
  };

  const handleWhatsAppShare = async () => {
    const raw = getShareMessage();
    const { opened, copied } = await openWhatsAppShare(raw);

    if (!opened) {
      toast.info(
        copied
          ? 'Message copied—paste it in WhatsApp to share.'
          : 'Could not open WhatsApp.'
      );
      return;
    }

    toast.success('Opening WhatsApp...');
  };

  const handleEmailPrepare = () => {
    const typeLabel = reconciliationType === 'credit-card' ? 'Credit Card' : 'Bank';
    setEmailSubject(`${typeLabel} Reconciliation Report - ${accountName} - ${formatDate(statementDate)}`);
    setEmailBody(getShareMessage());
    setEmailDialogOpen(true);
  };

  const handleEmailSend = () => {
    if (!emailTo.trim()) {
      toast.error('Please enter a recipient email address');
      return;
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(emailTo.trim())) {
      toast.error('Please enter a valid email address');
      return;
    }

    const mailtoUrl = `mailto:${encodeURIComponent(emailTo)}?subject=${encodeURIComponent(emailSubject)}&body=${encodeURIComponent(emailBody)}`;
    window.location.href = mailtoUrl;
    setEmailDialogOpen(false);
    toast.success('Opening email client...');
  };

  return (
    <>
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button variant="outline" size="sm" className="gap-2">
            <Share2 className="w-4 h-4" />
            Share
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="w-48">
          <DropdownMenuItem onClick={onExportPdf} className="gap-2">
            <Download className="w-4 h-4" />
            Export PDF
          </DropdownMenuItem>
          {onExportExcel && (
            <DropdownMenuItem onClick={onExportExcel} className="gap-2">
              <FileSpreadsheet className="w-4 h-4" />
              Export Excel
            </DropdownMenuItem>
          )}
          <DropdownMenuItem onClick={handlePrint} className="gap-2">
            <Printer className="w-4 h-4" />
            Print
          </DropdownMenuItem>
          <DropdownMenuSeparator />
          <DropdownMenuItem onClick={handleEmailPrepare} className="gap-2">
            <Mail className="w-4 h-4" />
            Share via Email
          </DropdownMenuItem>
          <DropdownMenuItem onClick={handleWhatsAppShare} className="gap-2">
            <MessageCircle className="w-4 h-4" />
            Share via WhatsApp
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>

      {/* Email Dialog */}
      <Dialog open={emailDialogOpen} onOpenChange={setEmailDialogOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Mail className="w-5 h-5" />
              Share via Email
            </DialogTitle>
            <DialogDescription>
              Send this reconciliation summary via email. For the full PDF report, please export and attach it manually.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="email-to">Recipient Email</Label>
              <Input
                id="email-to"
                type="email"
                placeholder="recipient@example.com"
                value={emailTo}
                onChange={(e) => setEmailTo(e.target.value)}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email-subject">Subject</Label>
              <Input
                id="email-subject"
                value={emailSubject}
                onChange={(e) => setEmailSubject(e.target.value)}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email-body">Message</Label>
              <Textarea
                id="email-body"
                rows={8}
                value={emailBody}
                onChange={(e) => setEmailBody(e.target.value)}
                className="font-mono text-sm"
              />
            </div>
            <div className="flex justify-end gap-2">
              <Button variant="outline" onClick={() => setEmailDialogOpen(false)}>
                Cancel
              </Button>
              <Button onClick={handleEmailSend} className="gap-2">
                <Mail className="w-4 h-4" />
                Open Email Client
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}
