import { jsPDF } from 'jspdf';
import { format } from 'date-fns';

interface AuditEvent {
  id: string;
  action: string;
  actorType: string;
  actorEmail?: string;
  timestamp: string;
  ipAddress?: string;
  details?: Record<string, unknown>;
}

interface CertificateData {
  documentId: string;
  documentTitle: string;
  documentHash?: string;
  events: AuditEvent[];
  signers?: { email: string; name?: string; signedAt?: string; ipAddress?: string }[];
}

export function generateAuditCertificate(data: CertificateData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = 20;

  // Header
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Document Signing Certificate', pageWidth / 2, y, { align: 'center' });
  y += 12;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Electronic Signature Audit Trail', pageWidth / 2, y, { align: 'center' });
  y += 15;

  // Document Info Box
  doc.setDrawColor(200);
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(margin, y, pageWidth - margin * 2, 45, 3, 3, 'FD');
  y += 8;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Document Title:', margin + 5, y);
  doc.setFont('helvetica', 'normal');
  doc.text(data.documentTitle || 'Untitled Document', margin + 40, y);
  y += 7;

  doc.setFont('helvetica', 'bold');
  doc.text('Document ID:', margin + 5, y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.text(data.documentId, margin + 40, y);
  y += 7;

  doc.setFontSize(9);
  if (data.documentHash) {
    doc.setFont('helvetica', 'bold');
    doc.text('SHA-256 Hash:', margin + 5, y);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6);
    doc.text(data.documentHash, margin + 40, y);
    y += 7;
  }

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Certificate Date:', margin + 5, y);
  doc.setFont('helvetica', 'normal');
  doc.text(format(new Date(), 'PPPp'), margin + 40, y);
  y += 15;

  // Signers Section
  if (data.signers && data.signers.length > 0) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Signers', margin, y);
    y += 8;

    doc.setFontSize(8);
    data.signers.forEach((signer, index) => {
      if (y > 260) {
        doc.addPage();
        y = 20;
      }

      doc.setFont('helvetica', 'bold');
      doc.text(`${index + 1}. ${signer.name || signer.email}`, margin + 5, y);
      y += 5;

      doc.setFont('helvetica', 'normal');
      doc.text(`Email: ${signer.email}`, margin + 10, y);
      y += 4;

      if (signer.signedAt) {
        doc.text(`Signed: ${format(new Date(signer.signedAt), 'PPPp')}`, margin + 10, y);
        y += 4;
      }

      if (signer.ipAddress) {
        doc.text(`IP Address: ${signer.ipAddress}`, margin + 10, y);
        y += 4;
      }
      y += 3;
    });
    y += 5;
  }

  // Audit Trail Section
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Audit Trail', margin, y);
  y += 8;

  doc.setFontSize(7);
  data.events.forEach((event) => {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }

    const timestamp = format(new Date(event.timestamp), 'yyyy-MM-dd HH:mm:ss');
    const action = event.action.replace(/_/g, ' ').replace(/\b\w/g, (l) => l.toUpperCase());
    const actor = event.actorEmail || event.actorType || 'System';

    doc.setFont('helvetica', 'bold');
    doc.text(`${timestamp}`, margin + 5, y);
    doc.setFont('helvetica', 'normal');
    doc.text(`${action} by ${actor}`, margin + 45, y);

    if (event.ipAddress) {
      doc.text(`(IP: ${event.ipAddress})`, margin + 140, y);
    }
    y += 5;
  });

  // Footer
  y = 280;
  doc.setDrawColor(200);
  doc.line(margin, y - 5, pageWidth - margin, y - 5);
  doc.setFontSize(7);
  doc.setFont('helvetica', 'italic');
  doc.text(
    'This document provides a record of all signing activities. The SHA-256 hash can be used to verify document integrity.',
    pageWidth / 2,
    y,
    { align: 'center' }
  );
  doc.text(
    `Generated by eFinsuite Globe on ${format(new Date(), 'PPPp')}`,
    pageWidth / 2,
    y + 4,
    { align: 'center' }
  );

  // Download
  const filename = `audit_certificate_${data.documentId.slice(0, 8)}_${format(new Date(), 'yyyy-MM-dd')}.pdf`;
  doc.save(filename);
}
