import { useCallback } from "react";
import { useMessaging } from "./useMessaging";
import { useTwilioShare } from "./useTwilioShare";
import { toast } from "sonner";
import * as XLSX from "xlsx";
import jsPDF from "jspdf";
import { parseContentToSheets } from "@/lib/parseContentToSheets";

interface ShareOptions {
  content: string;
  title?: string;
  format?: "text" | "pdf" | "excel" | "word";
}

export function useAliceShare() {
  const { sendEmail, sendSMS, sendWhatsApp } = useMessaging();
  const { shareWhatsAppNoRecipient, shareSMSNoRecipient } = useTwilioShare({ fallbackToApp: true });

  // Generate report content with Alice branding
  const formatReport = useCallback((content: string, title?: string): string => {
    const now = new Date().toLocaleString();
    return `
═══════════════════════════════════════════════════════════════
                    ALICE BUSINESS ADVISOR REPORT
                         EFinSuite Globe
═══════════════════════════════════════════════════════════════

${title ? `📋 ${title}\n` : ''}📅 Generated: ${now}

───────────────────────────────────────────────────────────────

${content}

───────────────────────────────────────────────────────────────
💡 This report was generated by Alice, your AI Business Advisor
   Powered by EFinSuite Globe
═══════════════════════════════════════════════════════════════
`.trim();
  }, []);

  // Share via Email
  const shareViaEmail = useCallback(async (
    to: string, 
    content: string, 
    subject?: string
  ): Promise<boolean> => {
    const report = formatReport(content, subject);
    const htmlContent = `
      <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto;">
        <div style="background: linear-gradient(135deg, #2563eb, #1e40af); padding: 20px; border-radius: 8px 8px 0 0;">
          <h1 style="color: white; margin: 0; font-size: 24px;">Alice Business Advisor</h1>
          <p style="color: rgba(255,255,255,0.8); margin: 5px 0 0;">EFinSuite Globe</p>
        </div>
        <div style="background: #f9fafb; padding: 20px; border: 1px solid #e5e7eb;">
          ${subject ? `<h2 style="color: #1e40af; margin-bottom: 16px;">${subject}</h2>` : ''}
          <div style="white-space: pre-wrap; font-size: 14px; line-height: 1.6; color: #374151;">
            ${content.replace(/\n/g, '<br>')}
          </div>
        </div>
        <div style="background: #1e40af; padding: 16px; border-radius: 0 0 8px 8px; text-align: center;">
          <p style="color: rgba(255,255,255,0.8); margin: 0; font-size: 12px;">
            Generated by Alice, AI Business Advisor • EFinSuite Globe
          </p>
        </div>
      </div>
    `;
    
    const result = await sendEmail(
      to,
      subject || "Alice Business Advisor Report",
      report,
      htmlContent
    );
    
    if (result.success) {
      toast.success("Report sent via email");
      return true;
    } else {
      toast.error(result.error || "Failed to send email");
      return false;
    }
  }, [sendEmail, formatReport]);

  // Share via SMS (opens composer or sends if backend available)
  const shareViaSMS = useCallback(async (content: string): Promise<void> => {
    const shortContent = content.length > 1000 
      ? content.slice(0, 997) + "..." 
      : content;
    await shareSMSNoRecipient(`Alice Advisor:\n${shortContent}`);
    toast.success("SMS ready to send");
  }, [shareSMSNoRecipient]);

  // Share via WhatsApp (opens app)
  const shareViaWhatsApp = useCallback(async (content: string): Promise<void> => {
    const message = `*Alice Business Advisor*\n_EFinSuite Globe_\n\n${content}`;
    await shareWhatsAppNoRecipient(message);
    toast.success("WhatsApp ready to send");
  }, [shareWhatsAppNoRecipient]);

  // Share via Google Chat (opens in browser)
  const shareViaGoogleChat = useCallback((content: string): void => {
    const encodedText = encodeURIComponent(`Alice Business Advisor\n\n${content}`);
    window.open(`https://chat.google.com/`, '_blank');
    // Copy to clipboard for pasting
    navigator.clipboard.writeText(`Alice Business Advisor\n\n${content}`);
    toast.success("Content copied - paste in Google Chat");
  }, []);

  // Download as PDF
  const downloadAsPDF = useCallback((content: string, filename?: string): void => {
    const doc = new jsPDF();
    const now = new Date().toLocaleString();
    
    // Header
    doc.setFillColor(37, 99, 235);
    doc.rect(0, 0, 210, 35, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.text("Alice Business Advisor", 14, 18);
    doc.setFontSize(10);
    doc.text("EFinSuite Globe", 14, 26);
    doc.text(now, 196, 26, { align: 'right' });
    
    // Content
    doc.setTextColor(55, 65, 81);
    doc.setFontSize(11);
    
    const lines = doc.splitTextToSize(content, 180);
    let y = 45;
    const pageHeight = 280;
    
    for (const line of lines) {
      if (y > pageHeight) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, 14, y);
      y += 6;
    }
    
    // Footer
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    doc.text("Generated by Alice, AI Business Advisor • EFinSuite Globe", 105, 290, { align: 'center' });
    
    doc.save(filename || `alice-report-${Date.now()}.pdf`);
    toast.success("PDF downloaded");
  }, []);

  // Download as Excel with smart content parsing
  const downloadAsExcel = useCallback((content: string, filename?: string): void => {
    const now = new Date().toLocaleString();
    const sheets = parseContentToSheets(content);
    const wb = XLSX.utils.book_new();

    sheets.forEach((sheet, idx) => {
      const wsData: (string | number)[][] = [];

      // Add header on first sheet
      if (idx === 0) {
        wsData.push(["Alice Business Advisor Report"]);
        wsData.push(["EFinSuite Globe"]);
        wsData.push(["Generated:", now]);
        wsData.push([]);
      }

      // Add sheet data
      wsData.push(...sheet.data);

      const ws = XLSX.utils.aoa_to_sheet(wsData);

      // Auto-size columns based on content
      const maxCols = Math.max(...wsData.map(r => r.length), 1);
      const colWidths: { wch: number }[] = [];
      for (let c = 0; c < maxCols; c++) {
        let maxLen = 10;
        wsData.forEach(row => {
          const cellLen = String(row[c] ?? '').length;
          if (cellLen > maxLen) maxLen = cellLen;
        });
        colWidths.push({ wch: Math.min(maxLen + 2, 60) });
      }
      ws['!cols'] = colWidths;

      // Apply number format to numeric cells
      const range = XLSX.utils.decode_range(ws['!ref'] || 'A1');
      for (let R = range.s.r; R <= range.e.r; R++) {
        for (let C = range.s.c; C <= range.e.c; C++) {
          const addr = XLSX.utils.encode_cell({ r: R, c: C });
          const cell = ws[addr];
          if (cell && typeof cell.v === 'number') {
            if (cell.v >= -1 && cell.v <= 1 && cell.v !== 0 && String(sheet.data[R]?.[C]).includes('%')) {
              cell.z = '0.00%';
            } else {
              cell.z = '#,##0.00';
            }
          }
        }
      }

      XLSX.utils.book_append_sheet(wb, ws, sheet.name);
    });

    XLSX.writeFile(wb, filename || `alice-report-${Date.now()}.xlsx`);
    toast.success("Excel file downloaded");
  }, []);

  // Download as Word (using HTML for better compatibility)
  const downloadAsWord = useCallback((content: string, filename?: string): void => {
    const now = new Date().toLocaleString();
    
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>Alice Business Advisor Report</title>
        <style>
          body { font-family: 'Calibri', sans-serif; margin: 40px; }
          .header { background: #2563eb; color: white; padding: 20px; margin: -40px -40px 30px; }
          .content { white-space: pre-wrap; line-height: 1.6; }
          .footer { margin-top: 40px; color: #9ca3af; font-size: 12px; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 20px; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1 style="margin: 0;">Alice Business Advisor</h1>
          <p style="margin: 5px 0 0; opacity: 0.8;">EFinSuite Globe • ${now}</p>
        </div>
        <div class="content">${content.replace(/\n/g, '<br>')}</div>
        <div class="footer">Generated by Alice, AI Business Advisor • EFinSuite Globe</div>
      </body>
      </html>
    `;
    
    const blob = new Blob([htmlContent], { type: 'application/msword' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename || `alice-report-${Date.now()}.doc`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success("Word document downloaded");
  }, []);

  // Download as plain text
  const downloadAsText = useCallback((content: string, filename?: string): void => {
    const report = formatReport(content);
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename || `alice-report-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success("Text file downloaded");
  }, [formatReport]);

  // Copy to clipboard
  const copyToClipboard = useCallback(async (content: string): Promise<void> => {
    try {
      await navigator.clipboard.writeText(content);
      toast.success("Copied to clipboard");
    } catch {
      toast.error("Failed to copy");
    }
  }, []);

  return {
    shareViaEmail,
    shareViaSMS,
    shareViaWhatsApp,
    shareViaGoogleChat,
    downloadAsPDF,
    downloadAsExcel,
    downloadAsWord,
    downloadAsText,
    copyToClipboard,
  };
}
