import jsPDF from 'jspdf';
import type { TaxSlip } from '@/hooks/useTaxSlips';
import { getPayrollPdfConfig, type SlipFieldSpec } from './slipFieldMapping';

interface GenericSlipData {
  slip: TaxSlip;
  countryCode: string;
  currencyCode: string;
  currencyLocale: string;
  employerName: string;
  employerAddress?: string;
  employerTaxId?: string;
  employerAccountNumber?: string;
}

const resolveField = (slip: TaxSlip, source: SlipFieldSpec['source']): number => {
  switch (source) {
    case 'gross': return slip.box_14_employment_income || 0;
    case 'incomeTax': return slip.box_22_income_tax_deducted || 0;
    case 'pension': return slip.box_16_cpp_contributions || 0;
    case 'socialInsurance': return slip.box_18_ei_premiums || 0;
    case 'insurableEarnings': return slip.box_24_ei_insurable_earnings || 0;
    case 'pensionableEarnings': return slip.box_26_cpp_pensionable_earnings || 0;
    default: return 0;
  }
};

export function generateGenericStatutorySlipPdf(data: GenericSlipData): void {
  const cfg = getPayrollPdfConfig(data.countryCode).slip;
  const doc = new jsPDF({ unit: 'mm', format: 'letter' });
  const pw = doc.internal.pageSize.getWidth();
  const M = 14;

  const money = (v: number) =>
    formatPdfCurrencyByCode(v || 0, data.currencyCode, data.currencyLocale);

  // Header bar
  doc.setFillColor(15, 38, 65);
  doc.rect(0, 0, pw, 24, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(cfg.formTitle, M, 10);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(cfg.authorityLine, M, 16);
  doc.setFontSize(9);
  doc.text(`Tax Year: ${data.slip.tax_year}`, pw - M, 10, { align: 'right' });
  doc.text(`Form: ${cfg.formCode}`, pw - M, 16, { align: 'right' });

  let y = 32;
  doc.setTextColor(0, 0, 0);

  // Employer / Employee blocks
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('EMPLOYER', M, y);
  doc.text('EMPLOYEE', pw / 2 + 4, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.text(data.employerName, M, y);
  const emp = data.slip.employees;
  const empName = emp ? `${emp.first_name || ''} ${emp.last_name || ''}`.trim() : 'Employee';
  doc.text(empName, pw / 2 + 4, y);
  y += 4.5;
  if (data.employerAddress) {
    const lines = doc.splitTextToSize(data.employerAddress, pw / 2 - M - 4);
    lines.forEach((l: string) => {
      doc.text(l, M, y);
      y += 4;
    });
  }
  if (data.employerTaxId || data.employerAccountNumber) {
    doc.text(
      `${cfg.taxIdLabel}: ${data.employerAccountNumber || data.employerTaxId}`,
      M,
      y,
    );
    y += 4.5;
  }

  // Employee side (right col)
  let ry = 42;
  doc.text(`Employee #: ${emp?.employee_number || ''}`, pw / 2 + 4, ry);
  ry += 4.5;
  const empAddr = [
    emp?.address_line1,
    emp?.address_line2,
    [emp?.city, emp?.province, emp?.postal_code].filter(Boolean).join(' '),
  ].filter(Boolean);
  empAddr.forEach((l) => {
    if (l) {
      doc.text(String(l), pw / 2 + 4, ry);
      ry += 4;
    }
  });

  y = Math.max(y, ry) + 6;

  // Boxes grid
  const contentW = pw - 2 * M;
  const cellW = contentW / 2;
  const cellH = 14;

  doc.setDrawColor(120);
  doc.setLineWidth(0.3);
  cfg.fields.forEach((f, i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const x = M + col * cellW;
    const cy = y + row * cellH;
    doc.rect(x, cy, cellW, cellH);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(80);
    doc.text(`${f.code}  ${f.label}`, x + 2, cy + 4);
    doc.setTextColor(0);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(money(resolveField(data.slip, f.source)), x + cellW - 3, cy + 10, { align: 'right' });
  });
  y += Math.ceil(cfg.fields.length / 2) * cellH + 6;

  // Notes
  if (data.slip.notes) {
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(80);
    const nl = doc.splitTextToSize(`Notes: ${data.slip.notes}`, contentW);
    doc.text(nl.slice(0, 4), M, y);
  }

  // Footer
  const ph = doc.internal.pageSize.getHeight();
  doc.setFontSize(7);
  doc.setTextColor(120);
  doc.text(
    `This is an official ${cfg.formCode} certificate. Retain for tax records.`,
    pw / 2,
    ph - 14,
    { align: 'center' },
  );
  doc.text('Generated by eFinsuite Globe  |  info@efintax.biz', pw / 2, ph - 10, {
    align: 'center',
  });
  if (data.slip.status) {
    doc.text(
      `Status: ${data.slip.status.toUpperCase()}${data.slip.issued_date ? '  |  Issued: ' + data.slip.issued_date : ''}`,
      pw / 2,
      ph - 6,
      { align: 'center' },
    );
  }

  const lastName = emp?.last_name || 'Employee';
  const firstName = emp?.first_name || '';
  doc.save(`${cfg.filenamePrefix}_${data.slip.tax_year}_${lastName}_${firstName}.pdf`);
}
